variables:
  GO_VERSION: "1.21.5"

image: golang:$GO_VERSION

stages:
  - lint
  - test

lint:
  stage: lint
  allow_failure: false
  before_script:
    - echo "Installing golangci-lint..."
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
    - echo "golangci-lint installed."

  script:
    - echo "Linting..."
    - golangci-lint run -v
    - echo "Linting complete."

test:
  stage: test
  script:
    - echo "Running tests..."
    - go test ./... -v
    - echo "Tests completed."
