stages:
  - trigger-child-pipelines

.base-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED == "true" # Trigger on MR to protected branches
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED == "true" # Trigger on push to protected branches
    - changes:
        - "**/*.gitlab-ci.yml" # Trigger on any changes to CI configuration
        - "*.gitlab-ci.yml"

trigger-go-pipeline:
  stage: trigger-child-pipelines
  trigger:
    include: "GO.gitlab-ci.yml"
    strategy: depend # Main pipeline success depends on the child pipeline
  rules:
    - !reference [.base-rules, rules]
    - changes:
        - "**/*.go"
        - "go.mod"
        - "go.sum"
      when: on_success
    - when: never # Catch-all to prevent this pipeline from unintentionally executing
