variables:
  GO_VERSION: "1.21.5"

image: golang:$GO_VERSION

stages:
  - lint
  - test
  - test-coverage

lint:
  stage: lint
  allow_failure: false
  before_script:
    - echo "Installing golangci-lint..."
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
    - echo "golangci-lint installed."

  script:
    - echo "Linting..."
    - golangci-lint run -v
    - echo "Linting complete."

test:
  stage: test
  script:
    - echo "Running tests..."
    - go test -v -coverprofile=coverage.txt -covermode count ./... # Runs tests, and generates code coverage at the same time
    - echo "Tests completed."

  artifacts:
    paths:
      - coverage.txt

test-coverage:
  stage: test-coverage
  needs: ["test"]

  before_script:
    - echo "Installing gocover-cobertura..."
    - go get github.com/boumenot/gocover-cobertura
    - echo "gocover-cobertura installed."

  script:
    - echo "Generating coverage report..."
    - go run github.com/boumenot/gocover-cobertura < coverage.txt > coverage.xml
    - echo "Coverage report generated."

  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
