variables:
  GO_VERSION: "1.22.5"
  GOLANGCI_LINT_VERSION: "1.56.2"
  GOCOVER_COBERTURA_VERSION: "1.2.0"

image: golang:$GO_VERSION

stages:
  - lint
  - test

lint:
  stage: lint
  allow_failure: false
  before_script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v$GOLANGCI_LINT_VERSION
  script:
    - golangci-lint run

test:
  stage: test
  before_script:
    - go install github.com/boumenot/gocover-cobertura@v$GOCOVER_COBERTURA_VERSION
  script:
    - go test -coverprofile=coverage.txt -covermode count ./... # Runs tests, and generates code coverage at the same time
    - gocover-cobertura < coverage.txt > coverage.xml
  coverage: '/coverage: \d+.\d+% of statements/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
